
seed: 42    # random seed for numpy default_rng(); use null for no seed

basepath: "./data"
inputpath: "./input"
outputpath: "./output"
waveformpath: "./waveforms"
datapath: "monte_carlo_comparisons_lightweight_500K_DWDs/initial_condition_variations/fiducial/"

duration: 2       # LISA observation time [years]
dt: 15            # cadence [seconds]; be mindful of the Nyquist frequency, 1/(2*dt)
use_gpu: false
icloop_kwargs:    # kwargs for gwg main loop
  maxiter: 10
  snr_thresh2: 49 # note that this is SNR^2
  tol: 0.05
  doplot: true    # plots from intermediate iterations are also saved to the output directory
  oversample: 1
  methoduse: "median"


